// GENERE (art)
export const PAL: any;
export const SKINS: any;
export const HAIRS: any;
export function clamp(...a: any[]): any;
export function esc(...a: any[]): any;
export function uid(...a: any[]): any;
export function rng(...a: any[]): any;
export function hex2rgb(...a: any[]): any;
export function rgb2hex(...a: any[]): any;
export function mix(...a: any[]): any;
export function shade(...a: any[]): any;
export function lum(...a: any[]): any;
export function textOn(...a: any[]): any;
export function initialsOf(...a: any[]): any;
export function nest(...a: any[]): any;
export const POSES: any;
export function player(...a: any[]): any;
export function gardien(...a: any[]): any;
export function coach(...a: any[]): any;
export function bust(...a: any[]): any;
export function poseVars(...a: any[]): any;
export function setExpr(...a: any[]): any;
export function setPose(...a: any[]): any;
export function toPose(...a: any[]): any;
export function idleCycle(...a: any[]): any;
export function runCycle(...a: any[]): any;
export function avatarOf(...a: any[]): any;
export function crest(...a: any[]): any;
export function ball(...a: any[]): any;
export function goal(...a: any[]): any;
export function stadiumSky(...a: any[]): any;
export function stadiumLights(...a: any[]): any;
export function stadiumCrowd(...a: any[]): any;
export function pitchPoint(...a: any[]): any;
export function stadiumPitch(...a: any[]): any;
export function stadium(...a: any[]): any;
export function scoreBug(...a: any[]): any;
export function lowerThird(...a: any[]): any;
export function cardFrame(...a: any[]): any;
export function rays(...a: any[]): any;
export function sparkle(...a: any[]): any;
export function speedLines(...a: any[]): any;
export function confetti(...a: any[]): any;
export function shake(...a: any[]): any;
export function countUp(...a: any[]): any;
export function crowdFlashes(...a: any[]): any;
export function sheen(...a: any[]): any;
export function trophy(...a: any[]): any;
export function medal(...a: any[]): any;
export function cardBack(...a: any[]): any;
export function cardPack(...a: any[]): any;
export function track(...a: any[]): any;
export function playerSide(...a: any[]): any;
export function setRunSide(...a: any[]): any;
export function runSide(...a: any[]): any;
