// GENERE (art)
export const PAL: any;
export const RARITY: any;
export function clamp(...a: any[]): any;
export function esc(...a: any[]): any;
export function uid(...a: any[]): any;
export function rng(...a: any[]): any;
export function hex2rgb(...a: any[]): any;
export function rgb2hex(...a: any[]): any;
export function mix(...a: any[]): any;
export function shade(...a: any[]): any;
export function r1(...a: any[]): any;
export function smooth(...a: any[]): any;
export function azulejoPattern(...a: any[]): any;
export function azulejoDataUri(...a: any[]): any;
export function papelPicado(...a: any[]): any;
export function paperGrainFilter(...a: any[]): any;
export function cornerOrnament(...a: any[]): any;
export const QUETZAL_PIVOT: any;
export function quetzal(...a: any[]): any;
export const QUETZAL_POSES: any;
export function quetzalSet(...a: any[]): any;
export function quetzalPoseTo(...a: any[]): any;
export function quetzalFlap(...a: any[]): any;
export function quetzalTalk(...a: any[]): any;
export function quetzalBlink(...a: any[]): any;
export function quetzalSway(...a: any[]): any;
export function quetzalRegrow(...a: any[]): any;
export const SOMBRA_PIVOT: any;
export function sombra(...a: any[]): any;
export function sombraFloat(...a: any[]): any;
export function sombraEyes(...a: any[]): any;
export function sombraDissolve(...a: any[]): any;
export const MONUMENTS: any;
export function monument(...a: any[]): any;
export function monumentSvg(...a: any[]): any;
export const MAP_W: any;
export function mapProj(...a: any[]): any;
export const MAP_REGIONS: any;
export const MAP_ROUTE: any;
export function mapRegion(...a: any[]): any;
export function worldMap(...a: any[]): any;
export function mapCam(...a: any[]): any;
export function mapCamTo(...a: any[]): any;
export function mapCamSet(...a: any[]): any;
export function mapFogClear(...a: any[]): any;
export function mapFogDrift(...a: any[]): any;
export function mapPulse(...a: any[]): any;
export function mapTravel(...a: any[]): any;
export function explainerMap(...a: any[]): any;
export function explainerReveal(...a: any[]): any;
