// GENERE (art)
export const PAL: any;
export const RARITY: any;
export function clamp(...a: any[]): any;
export function esc(...a: any[]): any;
export function uid(...a: any[]): any;
export function rng(...a: any[]): any;
export function hex2rgb(...a: any[]): any;
export function rgb2hex(...a: any[]): any;
export function mix(...a: any[]): any;
export function shade(...a: any[]): any;
export function r1(...a: any[]): any;
export function smooth(...a: any[]): any;
export function azulejoPattern(...a: any[]): any;
export function azulejoDataUri(...a: any[]): any;
export function papelPicado(...a: any[]): any;
export const FRIEZE_PAL: any;
export function azulejoFrieze(...a: any[]): any;
export const FILETE_PAL: any;
export function fileteFrieze(...a: any[]): any;
export function bunting(...a: any[]): any;
export function paperGrainFilter(...a: any[]): any;
export function cornerOrnament(...a: any[]): any;
export const QUETZAL_PIVOT: any;
export function quetzal(...a: any[]): any;
export const QUETZAL_POSES: any;
export function quetzalSet(...a: any[]): any;
export function quetzalPoseTo(...a: any[]): any;
export function quetzalFlap(...a: any[]): any;
export function quetzalTalk(...a: any[]): any;
export function quetzalBlink(...a: any[]): any;
export function quetzalSway(...a: any[]): any;
export function quetzalRegrow(...a: any[]): any;
export const COLOMBIA_PAL: any;
export const ANDES_PAL: any;
export function chakanaPath(...a: any[]): any;
export function colombiaFrieze(...a: any[]): any;
export function andesFrieze(...a: any[]): any;
export const SOMBRA_PIVOT: any;
export function sombra(...a: any[]): any;
export function sombraFloat(...a: any[]): any;
export function sombraEyes(...a: any[]): any;
export function sombraDissolve(...a: any[]): any;
export const MONUMENTS: any;
export function monument(...a: any[]): any;
export function monumentSvg(...a: any[]): any;
export const MAP_W: any;
export function mapProj(...a: any[]): any;
export const MAP_REGIONS: any;
export const MAP_ROUTE: any;
export const MAP_SPUR: any;
export const MAP_SEGMENTS: any;
export function mapRegion(...a: any[]): any;
export function mapFogHtml(...a: any[]): any;
export function cloudSvg(...a: any[]): any;
export function worldMap(...a: any[]): any;
export function mapCam(...a: any[]): any;
export function mapCamTo(...a: any[]): any;
export function mapCamMove(...a: any[]): any;
export function mapCamSet(...a: any[]): any;
export function mapFogClear(...a: any[]): any;
export function mapFogDrift(...a: any[]): any;
export function mapPulse(...a: any[]): any;
export function mapTravel(...a: any[]): any;
export function explainerMap(...a: any[]): any;
export function explainerReveal(...a: any[]): any;
export function sparklePath(...a: any[]): any;
export const SKY: any;
export function madridSkyline(...a: any[]): any;
export const ROOM: any;
export function academiaRoom(...a: any[]): any;
export function featherSvg(...a: any[]): any;
export function flagSvg(...a: any[]): any;
export function moteField(...a: any[]): any;
export const CHAR_PIVOT: any;
export const CHARS: any;
export function character(...a: any[]): any;
export function charTalk(...a: any[]): any;
export function charBlink(...a: any[]): any;
export function charIdle(...a: any[]): any;
export function charWalk(...a: any[]): any;
export function charWave(...a: any[]): any;
export function charEmote(...a: any[]): any;
export function charNod(...a: any[]): any;
export function prop(...a: any[]): any;
export function storkSvg(...a: any[]): any;
export function frozenKid(...a: any[]): any;
export function fachadaUniversidad(...a: any[]): any;
export function salamancaSkyline(...a: any[]): any;
export const PATIO: any;
export function colegioPatio(...a: any[]): any;
export const AULA: any;
export function aula(...a: any[]): any;
export function sevillaSkyline(...a: any[]): any;
export const CALLEJON: any;
export function callejonTriana(...a: any[]): any;
export const PATIOA: any;
export function patioAndaluz(...a: any[]): any;
export const TALLER: any;
export function tallerCeramica(...a: any[]): any;
export function coyoacanSkyline(...a: any[]): any;
export const PLAZA: any;
export function plazaHidalgo(...a: any[]): any;
export function casaAzulFachada(...a: any[]): any;
export function mxBalloonSvg(...a: any[]): any;
export const CASAP: any;
export function casaAzulPatio(...a: any[]): any;
export function autorretrato(...a: any[]): any;
export function mxProp(...a: any[]): any;
export function ofrendaSvg(...a: any[]): any;
export function oxProp(...a: any[]): any;
export function oxSeal(...a: any[]): any;
export const OAXACA_SKY: any;
export function oaxacaSkyline(...a: any[]): any;
export function oaxacaStall(...a: any[]): any;
export const OX_PATIO: any;
export function patioOfrenda(...a: any[]): any;
export function oaxacaPetalPath(...a: any[]): any;
export function bogotaSkyline(...a: any[]): any;
export const CALLE: any;
export function calleCandelaria(...a: any[]): any;
export function bgSignPost(...a: any[]): any;
export function bgCityMap(...a: any[]): any;
export function bgLetterSvg(...a: any[]): any;
export function bgColombiaMap(...a: any[]): any;
export function bgOroVitrina(...a: any[]): any;
export function bgTeleferico(...a: any[]): any;
export function bgPlazaCard(...a: any[]): any;
export function bgStreetCard(...a: any[]): any;
export function bgCyclist(...a: any[]): any;
export function bgWalker(...a: any[]): any;
export function bgCiclovia(...a: any[]): any;
export function vlDigital(...a: any[]): any;
export function vlAlarm(...a: any[]): any;
export function vlClock(...a: any[]): any;
export function vlPaella(...a: any[]): any;
export function vlSkyline(...a: any[]): any;
export const VLPLAZA: any;
export function vlPlaza(...a: any[]): any;
export function vlProp(...a: any[]): any;
export function vlCrowd(...a: any[]): any;
export const MN_PLAZA: any;
export function mnPlaza(...a: any[]): any;
export function mnSkyline(...a: any[]): any;
export function mnProp(...a: any[]): any;
export function yucatanSkyline(...a: any[]): any;
export const SELVA: any;
export function selvaSentier(...a: any[]): any;
export function yuGlyph(...a: any[]): any;
export const CASTILLO: any;
export function elCastillo(...a: any[]): any;
export const CIMA: any;
export function templeCima(...a: any[]): any;
export const CENOTE: any;
export function cenote(...a: any[]): any;
export function yuFlamingo(...a: any[]): any;
export function yuPyramidPlan(...a: any[]): any;
export function yuPyramidSide(...a: any[]): any;
export function yuTenochtitlan(...a: any[]): any;
export function yuCiudad(...a: any[]): any;
export function yuFood(...a: any[]): any;
export function baSkyline(...a: any[]): any;
export const BA_CAM: any;
export function baCaminito(...a: any[]): any;
export const BA_TEL: any;
export function baSanTelmo(...a: any[]): any;
export function baPareja(...a: any[]): any;
export function baProp(...a: any[]): any;
export function baArgentina(...a: any[]): any;
export function cuLlama(...a: any[]): any;
export function cuCondor(...a: any[]): any;
export const CUSCO: any;
export function cuscoSkyline(...a: any[]): any;
export const PLAZA_ARMAS: any;
export function plazaDeArmas(...a: any[]): any;
export const ESCAL: any;
export function escalinata(...a: any[]): any;
export const MUROS: any;
export function murosIncas(...a: any[]): any;
export const VISTA: any;
export function andesVista(...a: any[]): any;
export const MACHU: any;
export function machuPicchu(...a: any[]): any;
export const PERU_VIEW: any;
export function peruProj(...a: any[]): any;
export function peruMap(...a: any[]): any;
export function cuProp(...a: any[]): any;
