import { open, seed } from './lib.mjs';
const [quest, from] = [process.argv[2] || 'u01-q02', process.argv[3] || '0'];
const { browser, page } = await open(`from=${from}`);
page.on('requestfailed', (r) => console.log('REQFAILED', r.url()));
page.on('response', (r) => { if (r.status() >= 400) console.log('HTTP', r.status(), r.url()); });
await seed(page);
await page.evaluate((q) => window.__q.nav.go({ name: 'quest', quest: q }), quest);
await page.waitForTimeout(2500);
const info = await page.evaluate(() => [...document.querySelectorAll('img')].map((i) => `${i.src.split('/').pop()} ${i.naturalWidth} ${i.complete}`));
console.log(info.join('\n'));
console.log((await page.evaluate(() => document.body.innerText)).slice(0, 400));
await browser.close();
