import { chromium } from 'playwright-core';
const browser = await chromium.launch({ channel: 'chrome', headless: true });
const ctx = await browser.newContext({ viewport: { width: 1280, height: 800 }, hasTouch: true });
const page = await ctx.newPage();
page.on('pageerror', (e) => console.log('PAGEERROR', e.message));
await page.goto('http://127.0.0.1:5199/espagnol/?debug');
await page.waitForSelector('text=¡Empezar!');
await page.click('text=¡Empezar!');
await page.waitForSelector('.welc input');
await page.fill('.welc input', 'Josu');
await page.click('.welc .key:has-text("é")');
await page.click('button:has-text("Me llamo Josué")');
await page.waitForTimeout(2000);
console.log(await page.evaluate(() => [...document.querySelectorAll('.welc *')].map((e) => e.className && typeof e.className === 'string' ? e.className.split(' ')[0] : '').filter((c) => c && !c.startsWith('m-') && !c.startsWith('q-')).join(' ')));
await browser.close();
