import { chromium } from 'playwright-core';
import { mkdirSync } from 'node:fs';
const out = 'tools/e2e/_dev/out';
mkdirSync(out, { recursive: true });
const browser = await chromium.launch({ channel: 'chrome', headless: true });
const ctx = await browser.newContext({ viewport: { width: 1280, height: 800 }, hasTouch: true });
const page = await ctx.newPage();
page.on('pageerror', (e) => console.log('PAGEERROR', e.message));
page.on('console', (m) => { if (['error', 'warning'].includes(m.type())) console.log('CONSOLE', m.type(), m.text().slice(0, 300)); });
await page.goto('http://127.0.0.1:5199/espagnol/');
await page.waitForTimeout(1500);
await page.screenshot({ path: `${out}/1-title.png` });
await page.click('text=¡Empezar!');
await page.waitForTimeout(1500);
await page.screenshot({ path: `${out}/2-name.png` });
await page.fill('input', 'Wael');
await page.click('button:has-text("Me llamo Wael")');
await page.waitForTimeout(1200);
await page.screenshot({ path: `${out}/3-avatar.png` });
await page.click('button:has-text("¡Listo!")');
await page.waitForTimeout(1800);
await page.screenshot({ path: `${out}/4-prologo.png` });
for (let i = 0; i < 4; i++) { await page.click('button:has-text("Siguiente")'); await page.waitForTimeout(900); }
await page.screenshot({ path: `${out}/5-prologo-sombra.png` });
await page.click('button:has-text("Siguiente")'); await page.waitForTimeout(900);
await page.click('button:has-text("¡Vamos!")');
await page.waitForTimeout(2500);
await page.screenshot({ path: `${out}/6-map.png` });
await browser.close();
